import streamlit as st
import pandas as pd
import yfinance as yf
import numpy as np
from alpaca.trading.client import TradingClient
from alpaca.trading.requests import MarketOrderRequest
from alpaca.trading.enums import OrderSide, TimeInForce
from transformers import AutoTokenizer, AutoModelForSequenceClassification
import torch
from st_paywall import add_auth
import stripe  # Final addition 1

# --- 0. CORE BRANDING & PROFESSIONAL THEME ---
st.set_page_config(
    page_title="CERBERUS | AI Research Suite", 
    page_icon="🐕‍🦺", 
    layout="wide",
    initial_sidebar_state="expanded"
)

# Final addition 2: Links your secrets to the stripe library
stripe.api_key = st.secrets["STRIPE_API_KEY"]

# Custom Institutional Blue CSS
st.markdown("""
    <style>
    .main { background-color: #0e1117; color: #f8fafc; }
    .stButton>button { 
        background: linear-gradient(90deg, #1e3a8a 0%, #3b82f6 100%); 
        color: white; border-radius: 8px; border: none; font-weight: 600;
        width: 100%; transition: 0.3s;
    }
    .stButton>button:hover { transform: scale(1.02); box-shadow: 0 4px 15px rgba(59, 130, 246, 0.4); }
    .stMetric { background-color: #1e293b; padding: 20px; border-radius: 12px; border: 1px solid #334155; }
    div[data-testid="stExpander"] { background-color: #1e293b; border: 1px solid #334155; border-radius: 10px; }
    .stSidebar { background-color: #0f172a; border-right: 1px solid #1e293b; }
    </style>
    """, unsafe_allow_html=True)

# 2026 PAYWALL GATEWAY
add_auth(required=True)

# --- 1. INITIALIZE SESSION STATE ---
if "api_connected" not in st.session_state:
    st.session_state.api_connected = False
if "trading_client" not in st.session_state:
    st.session_state.trading_client = None
if "calc_done" not in st.session_state:
    st.session_state.calc_done = False

# --- 2. THE LEGAL COMPLIANCE LAYER ---
def show_masthead_and_legal():
    st.title("🐕‍🦺 CERBERUS")
    st.caption("### Institutional Asset Research & Quantitative Sentiment Engine")
    
    with st.expander("⚖️ LEGAL DISCLOSURE & SERVICE TERMS (REQUIRED READING)", expanded=True):
        st.error("### IMPORTANT: NOT FINANCIAL ADVICE")
        st.markdown(f"""
        **Governance:** CERBERUS is an experimental data-visualization suite developed by **Harry Braime & Archie Pahl**.
        * **Mathematical Research:** All scores are generated by the FinBERT neural network and are probabilistic, not predictive.
        * **User Liability:** Founders are not registered investment advisors (RIA). You are 100% responsible for your capital.
        * **Subscription Transparency:** In accordance with the DMCC Act 2024, you can cancel your subscription at any time via the portal.
        """)

# --- 3. SIDEBAR NAVIGATION ---
with st.sidebar:
    st.header("System Access")
    st.markdown("---")
    st.write(f"**Founders:** Harry Braime & Archie Pahl")
    st.write(f"**User:** {st.session_state.get('user_email', 'Authenticated User')}")
    
    # Optional: Add a button for users to manage their subscription
    st.link_button("Manage Subscription", "https://billing.stripe.com/p/login/test_your_portal_link")
    st.divider()
    
    if not st.session_state.api_connected:
        st.subheader("Connect Alpaca Portfolio")
        api_key = st.text_input("API Key", type="password")
        sec_key = st.text_input("Secret Key", type="password")
        is_live = st.toggle("Live Market (REAL CAPITAL)", value=False)
        
        if st.button("Initialize Neural Link"):
            try:
                client = TradingClient(api_key, sec_key, paper=(not is_live))
                client.get_account() 
                st.session_state.trading_client = client
                st.session_state.api_connected = True
                st.success("Connection Secured")
                st.rerun()
            except Exception as e:
                st.error("Auth Failed: Verify keys and account status.")
    else:
        st.success("🟢 CORE ONLINE")
        if st.button("Disconnect Session"):
            st.session_state.api_connected = False
            st.rerun()

# --- 4. ENGINE FUNCTIONS ---
@st.cache_resource
def load_nlp_model():
    tokenizer = AutoTokenizer.from_pretrained("ProsusAI/finbert")
    model = AutoModelForSequenceClassification.from_pretrained("ProsusAI/finbert")
    return tokenizer, model

def get_clean_data(symbol):
    try:
        formatted_ticker = symbol.replace("/", "-").upper()
        df = yf.download(formatted_ticker, period="1y", interval="1d", progress=False)
        return df if not df.empty else None
    except:
        return None

# --- 5. MAIN INTERFACE ---
show_masthead_and_legal()

if st.session_state.api_connected:
    st.divider()
    col1, _ = st.columns([2, 1])
    with col1:
        ticker_input = st.text_input("Enter Asset Ticker (e.g., TSLA, BTC-USD, NVDA)", "AAPL").upper()
    
    if st.button("Generate Quantitative Intelligence Report"):
        with st.spinner("Processing market vectors through neural layers..."):
            data = get_clean_data(ticker_input)
            if data is not None:
                tokenizer, model = load_nlp_model()
                inputs = tokenizer([f"Sentiment analysis for {ticker_input}"], return_tensors="pt")
                outputs = model(**inputs)
                score = torch.nn.functional.softmax(outputs.logits, dim=-1)[0][0].item()
                
                st.session_state.current_score = score
                st.session_state.calc_done = True
                st.session_state.current_ticker = ticker_input
            else:
                st.error("Asset Ticker Invalid. Please check the symbol.")

    if st.session_state.calc_done:
        st.divider()
        st.subheader(f"Intelligence Dashboard: {st.session_state.current_ticker}")
        
        m1, m2, m3 = st.columns(3)
        m1.metric("Sentiment Confidence", f"{st.session_state.current_score:.2%}")
        m2.metric("Market Data", "Verified / Live")
        m3.metric("Neural Model", "FinBERT v1.2")

        if st.session_state.current_score > 0.6:
            st.info("💡 **RESEARCH NOTE:** High-confidence positive sentiment detected.")
            with st.container(border=True):
                st.write("### 🛒 Fast-Execution Terminal")
                if st.button(f"EXECUTE MARKET BUY: 1 unit of {st.session_state.current_ticker}"):
                    try:
                        trade_symbol = st.session_state.current_ticker.replace("-", "")
                        order = MarketOrderRequest(
                            symbol=trade_symbol,
                            qty=1,
                            side=OrderSide.BUY,
                            time_in_force=TimeInForce.GTC
                        )
                        st.session_state.trading_client.submit_order(order)
                        st.balloons()
                        st.success(f"SUCCESS: Market order for {trade_symbol} transmitted.")
                    except Exception as e:
                        st.error(f"Execution Failure: {e}")
        else:
            st.warning("📉 **RESEARCH NOTE:** Sentiment is neutral or negative.")

else:
    st.info("Please connect your secure API keys via the sidebar to access the research suite.")

# --- 6. FOOTER ---
st.divider()
st.caption(f"© 2026 Cerberus Quantitative Suite | Powered by Harry Braime & Archie Pahl.")
